# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  db:
    container_name: db-container
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz@WSX3edc
      MYSQL_DATABASE: myapi
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306

  nginx:
    container_name: nginx-container
    image: nginx:1.19.5-alpine
    volumes:
      - api_data:/docker_api
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

  web:
    container_name: web-container
    image: web
    build: .
    entrypoint: ["bash", "/code/entrypoint.sh"]
    command: uwsgi --ini /code/uwsgi.ini
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=mysql+mysqldb://admin:admin@db/myapi?charset=utf8
    volumes:        
      - api_data:/docker_api
    depends_on:
      - db

volumes:
  db_data:
  api_data:
